print("Enter two values:")
x = int(input())
y = int(input())
print("Additon is:", x + y)
print("Subtraction is:", x - y)
print("Multiplication is:", x * y)
print("Division is:", x / y)
print("Modulo division is:", x % y)
